version: "3"
services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NEXT_PUBLIC_BACKEND_APP: ${NEXT_PUBLIC_BACKEND_APP}
      NEXT_PUBLIC_FRONTEND_APP: ${NEXT_PUBLIC_FRONTEND_APP}
      NEXT_PUBLIC_API_BASE_URL_BACKEND: ${NEXT_PUBLIC_API_BASE_URL_BACKEND}
      NEXT_PUBLIC_API_BASE_URL_FRONTEND: ${NEXT_PUBLIC_API_BASE_URL_FRONTEND}
      AUTH_SECRET: ${AUTH_SECRET}
